version: '3.9'
services:
  db-postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: admin123
      POSTGRES_USER: docker
    ports:
      - 5432:5432
    expose:
      - 5432
    networks:
      - erudio-network
  rest-with-spring-boot-erudio:
    image: mvalentim/spring_restful
    restart: always
    build: C:/Desenvolvimento/Projetos_Backend/PersonRESTful/PersonRESTful
    working_dir: /PersonRESTful/PersonRESTful
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:postgresql://db-postgres:5432/spring_restful?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: docker
      SPRING.DATASOURCE.PASSWORD: admin123
    ports:
      - 8090:8090
    command: mvn spring-boot:run
    depends_on:
      - db-postgres
    networks:
      - erudio-network
networks:
  erudio-network:
    driver: bridge
