version: '3.9'
services:
  db:
    image: mysql:8
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: restful_erudio
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3309
    ports:
      - 3309:3309
    expose:
      - 3306
    networks:
      - erudio-network
  rest-with-spring-boot:
    image: mvalentim/restful_erudio
    restart: always
    build: C:/desenvolvimento/Projetos_Backend/PersonRESTful/
    working_dir: /PersonRESTful
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://0.0.0.0:3309/restful_erudio?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: docker
      SPRING.DATASOURCE.PASSWORD: admin123
    ports:
      - 8090:8090
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - erudio-network
networks:
  erudio-network:
    driver: bridge